export enum ArchitectureActorType {
  App = "📱 App",
  World = "🌐 World",
  ComponentSystem = "🧱 ComponentSystem",
  ComponentSystemGroup = "🧱📥 ComponentSystemGroup",
  InteractionSystemGroup = "👆📥 InteractionSystemGroup",
  CollaborationSystem = "👫 CollaborationSystem",
  InputSystem = "🕹 InputSystem",
  StorySystem = "🧧 StorySystem",
  InteractionSystem = "👆 InteractionSystem",
  WelcomeParticipantsStorySystem = "👋 WelcomeParticipantsStorySystem",
  ElementSystem = "🎛 ElementSystem",
  Entity = "💎 Entity",
  EntityManager = "🎬 EntityManager",
  EntityQuery = "💬 EntityQuery",
  UniversalEntityQuery = "💬 UniversalEntityQuery",
}
